### ISSUE TITLE
GDAL Warp error

### ISSUE THREAD

**Issue by mcovalt** [ResonantGeoData/ResonantGeoData#526] opened 2021-09-23 16:03 UTC
GDAL has been complaining in our CI tests:

```python
../../.tox/test-rgd-imagery/lib/python3.8/site-packages/large_image_source_gdal/__init__.py:1137: in getRegion
    gdal.Warp(outputPath, ds, options=gdalParams)
        __class__  = <class 'large_image_source_gdal.GDALFileTileSource'>
        br         = (334.0, 628.0)
        ds         = <osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f28b9356630> >
        fd         = 23
        format     = ('image',)
        gdalParams = ['-of', 'COG', '-co', 'BIGTIFF=IF_SAFER', '-co', 'BLOCKSIZE=256', ...]
        iterInfo   = {'encoding': 'TILED', 'format': ('numpy',), 'frame': None, 'level': 2, ...}
        kwargs     = {'encoding': 'TILED', 'region': {'bottom': 627.64, 'left': 19.23, 'right': 333.73, 'top': 383.18, ...}}
        outHeight  = 245
        outWidth   = 315
        outputPath = '/tmp/tiledGeoRegion_uptqomyj.tiff'
        self       = <large_image_source_gdal.GDALFileTileSource object at 0x7f28b937a8b0>
        srs        = None
        tl         = (19.0, 383.0)
        useGDALWarp = True
../../.tox/test-rgd-imagery/lib/python3.8/site-packages/osgeo/gdal.py:673: in Warp
    (opts, callback, callback_data) = WarpOptions(**kwargs)
        destNameOrDestDS = '/tmp/tiledGeoRegion_uptqomyj.tiff'
        kwargs     = {'options': ['-of', 'COG', '-co', 'BIGTIFF=IF_SAFER', '-co', 'BLOCKSIZE=256', ...]}
        srcDSOrSrcDSTab = <osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f28b9356630> >
../../.tox/test-rgd-imagery/lib/python3.8/site-packages/osgeo/gdal.py:660: in WarpOptions
    return (GDALWarpAppOptions(new_options), callback, callback_data)
        callback   = None
        callback_data = None
        coordinateOperation = None
        copyMetadata = True
        creationOptions = None
        cropToCutline = False
        cutlineBlend = None
        cutlineDSName = None
        cutlineLayer = None
        cutlineSQL = None
        cutlineWhere = None
        dstAlpha   = False
        dstNodata  = None
        dstSRS     = None
        errorThreshold = None
        format     = None
        geoloc     = False
        height     = 0
        metadataConflictValue = None
        multithread = False
        new_options = ['-of', 'COG', '-co', 'BIGTIFF=IF_SAFER', '-co', 'BLOCKSIZE=256', ...]
        options    = ['-of', 'COG', '-co', 'BIGTIFF=IF_SAFER', '-co', 'BLOCKSIZE=256', ...]
        outputBounds = None
        outputBoundsSRS = None
        outputType = 0
        overviewLevel = 'AUTO'
        polynomialOrder = None
        resampleAlg = None
        rpc        = False
        setColorInterpretation = False
        srcAlpha   = False
        srcNodata  = None
        srcSRS     = None
        targetAlignedPixels = False
        tps        = False
        transformerOptions = None
        warpMemoryLimit = None
        warpOptions = None
        width      = 0
        workingType = 0
        xRes       = None
        yRes       = None
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <osgeo.gdal.GDALWarpAppOptions;  >
args = (['-of', 'COG', '-co', 'BIGTIFF=IF_SAFER', '-co', 'BLOCKSIZE=256', ...],)

    def __init__(self, *args):
        """__init__(GDALWarpAppOptions self, char ** options) -> GDALWarpAppOptions"""
>       this = _gdal.new_GDALWarpAppOptions(*args)
E       TypeError: sequence must contain strings

args       = (['-of', 'COG', '-co', 'BIGTIFF=IF_SAFER', '-co', 'BLOCKSIZE=256', ...],)
self       = <osgeo.gdal.GDALWarpAppOptions;  >

../../.tox/test-rgd-imagery/lib/python3.8/site-packages/osgeo/gdal.py:4667: TypeError
```

**Comment by manthey** [comment] 2021-09-24 19:47
This is caused by trying to subset a non-geospatial input file.  Specifically, large_image is calling gdal.Warp with a `-t_srs` parameter of `None`.  It will need to be fixed in large_image.

**Comment by manthey** [comment] 2021-09-24 20:07
This will be resolved by https://github.com/girder/large_image/pull/662

**Closed** 2021-09-27 12:36 UTC
Labels: bug
